# CircleCI 2.0 configuration file.
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details.

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - version-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - version-dependencies-
      - run: npm install
      - run: npm run build
      - save_cache:
          paths:
            - node_modules
            - .cache
          key: version-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ./
          paths:
            - dist
            - node_modules  # added to use push-dir
  deploy:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/project
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "4e:68:fa:44:f8:be:20:c4:b7:69:7d:c0:4c:15:df:dc"
      - attach_workspace:
          at: dist
      - run:
          name: configure git 1
          command: git config user.email "njncalub@gmail.com"
      - run:
          name: configure git 2
          command: git config user.name "Nap Joseph Calub"
      - run:
          name: Deploy to gh-pages branch
          command: npm run push-gh-pages
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
